site_name: notes
docs_dir: src
site_dir: out

theme:
  name: material
  collapse_navigation: true   # enable collapsing
  navigation_depth: 3       # show nested levels (must be >1)
  sticky_navigation: true   
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - tables: {}
  - extra: {}
  - def_list: {}
  - toc:
      permalink: ""
      separator: "_"
  - admonition: {}

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Chapter 1:
      - Intro: chapter1/intro.md
      - Lesson 1: chapter1/lesson-1.md
  - Chapter 2:
      - Overview: chapter2/overview.md
