name: Build & Deploy Docs (HTML + PDF)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install MkDocs + theme(s)
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-rtd-dropdown

      - name: Install Pandoc + Tectonic (PDF engine)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc tectonic

      - name: Build HTML + PDF
        run: |
          # HTML (uses the theme configured in mkdocs.yml)
          mkdocs build --clean
          # PDF via Pandoc + Tectonic
          make pdf PDFENG=tectonic
          # Ensure the PDF sits in 'out/' so it gets published
          test -f out/documentation.pdf

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
